fix#372
sohosai/sos24-client pull request #390
Opened 2024-06-09 07:56 UTC by naohanpen

2024-06-09 09:31 UTC, appare45 requested changes
スミマセン、事前にちゃんとissueを書かなかったのが悪いんですが、図のハンバーガーメニューをログアウトボタンにしてもらうことってできますか？
![image](https://github.com/sohosai/sos24-client/assets/64473501/65888404-4f00-412c-89eb-6324bd949a79)

2024-06-09 09:31 UTC, appare45 commented on package.json
> +    "sass": "^1.77.4",
```suggestion

```

2024-06-09 09:31 UTC, appare45 commented on src/common_components/header/SwitchModeButton.tsx
> +import style_SwitchModeButton from "@/common_components/header/SwitchModeButton.module.scss";
SCSSではなくpanda CSSに書き足す形にしてもらっても大丈夫ですか？

2024-06-09 11:38 UTC, naohanpen commented
@appare45 ハンバーガーメニューが出ていないのですが、自分の環境だけでしょうか...

2024-06-10 06:22 UTC, ishikawa-naota commented on src/common_components/header/SwitchModeButton.tsx
> +import style_SwitchModeButton from "@/common_components/header/SwitchModeButton.module.scss";
１ファイルがとても長くなりそうですが、大丈夫ですか？

2024-06-10 13:20 UTC, appare45 requested changes
色々いってしまって申し訳ないです 🙇 
（事前にもう少し共有しておけばよかったです、スミマセン）
確認のほどよろしくお願いいたします。

2024-06-10 13:20 UTC, appare45 commented on src/common_components/header/HeaderButton.tsx
> +}> = ({ text, icon, clickev }) => (
```suggestion
export const HeaderButton: FC<{
  children: ReactNode;
  icon: string;
  clickev: MouseEventHandler<HTMLButtonElement>;
}> = ({ children, icon, clickev }) => (
```
こんな感じにするとHeaderButtonの子要素が自動的にchildrenになるはずなのでこちらのほうが良いかと思います

2024-06-10 13:20 UTC, appare45 commented on src/common_components/header/HeaderButton.tsx
> +      fontSize: "sm",
```suggestion
      fontSize: {base: "sm", lg: "md"},
```
モバイル版だけで字が小さくなるようにお願いします

2024-06-10 13:20 UTC, appare45 commented on src/common_components/header/HeaderButton.tsx
> +      },
現状、SOSの中でhover/focusで色が変わる要素がないので、統一感を保つために全体でどういう方針にするかを話し合ったほうがいいかもしれないです

2024-06-10 13:20 UTC, appare45 commented on src/common_components/header/HeaderNavigationMobile.tsx
> +            },
同上

2024-06-10 13:20 UTC, appare45 commented on src/common_components/header/HeaderButton.tsx
> +      height: "100%",
```suggestion
      height: "full",
```
Panda CSSの[theme](https://panda-css.com/docs/customization/theme)を使うように統一しているのでお願いします

2024-06-10 13:20 UTC, appare45 commented on src/common_components/header/HeaderButton.tsx
> +      rounded: "5px",
```suggestion
      p: 2 2.5 0.5,
      rounded: "sm",
```

2024-06-10 13:20 UTC, appare45 commented on src/common_components/header/HeaderNavigationMobile.tsx
> +          base: "10px",
```suggestion
          base: 5,
          lg: "0",
        },
        marginX: {
          base: 2.5,
```

2024-06-10 13:20 UTC, appare45 commented on package-lock.json
`npm i` で更新したほうが良さそう

2024-06-10 13:58 UTC, ishikawa-naota commented on package-lock.json
間違えて merge しちゃってました🙏🏻

2024-06-12 00:03 UTC, appare45 reviewed
五月雨式になっていて申し訳ないです
一箇所だけ確認お願いします 🙏

2024-06-14 10:03 UTC, ishikawa-naota commented
deploy に失敗してるっぽいです、

2024-06-15 04:32 UTC, appare45 commented
なんかビルド通った

2024-06-15 04:35 UTC, appare45 approved these changes
LGTM!ありがとうございました！

2024-06-15 04:35 UTC, merged