fix#414
sohosai/sos24-client pull request #415
Opened 2024-07-17 19:15 UTC by naohanpen

- ファイル一覧の保持方法を変更
- 選択され次第アップロード

2024-07-18 15:16 UTC, appare45 commented
`npm ci`がこけてるけどなんでだろう

2024-07-19 01:54 UTC, naohanpen commented
設定とかは何も変えていないはずなのですが、、💦

2024-07-19 05:06 UTC, arata-nvm commented
https://github.com/npm/cli/issues/7657
これっぽそう

2024-07-19 06:20 UTC, appare45 requested changes
実装ありがとうございます！
確認お願いします

2024-07-19 06:20 UTC, appare45 commented on src/common_components/form_editor/FormEditor.tsx
> +    })) ?? [];
```suggestion
    defaultValues?.attachments.map((uuid) => {
    // ここでファイルのデータを取得する処理を書くと優しそう
    const { data, error: swrError, isLoading } = useSWR(`/files/${uuid}`);
    return ({
      name: null,
      uuid: uuid,
      uploaded: true,
    })}) ?? [];
```

2024-07-19 06:20 UTC, appare45 commented on src/common_components/form_editor/FormFiles.tsx
https://github.com/sohosai/sos24-client/blob/23e3fe2277fceede4ca29ae17445a743f57a5240/src/common_components/formFields/Files.tsx#L26
FilesFieldと統合しても良さそうですがどうでしょう？

2024-07-19 09:51 UTC, naohanpen commented on src/app/committee/forms/[form_id]/edit/page.tsx
> +        {/* <p>{JSON.stringify(defaultValues)}</p> */}
完全に忘れていました

2024-07-19 11:02 UTC, naohanpen commented on src/common_components/form_editor/FormFiles.tsx
送信形式が大きく変わっていて、FilesField2 みたいになっているのですが、しっかりコンポーネントにした方がよいでしょうか？

2024-07-19 11:05 UTC, naohanpen commented on src/common_components/form_editor/FormEditor.tsx
> +  const fileDatas =
英語力の無さが...失礼しました汗

2024-07-20 09:52 UTC, appare45 commented on src/common_components/form_editor/FormFiles.tsx
（対面で話した）どちらかの実装に統合すると良さそう
FormFiedl側を書き換えてしまっても良さそう

2024-07-20 10:16 UTC, naohanpen commented on src/common_components/form_editor/FormFiles.tsx
少し怖いですが統合しちゃってみます！笑

2024-07-27 09:42 UTC, appare45 commented
#424 とかなりコンフリクトしていそう

2024-07-28 15:50 UTC, appare45 requested changes
本当にお疲れ様＆ありがとうございます！
いくつかコメントしたので確認お願いします

2024-08-04 14:44 UTC, naohanpen commented
全然うまくいってなかった💦
- [ ] 申請作成時にファイルを添付できない
- [ ] 回答がないのに、回答が存在するという（申請詳細ページでは問題ないが、申請編集ページではエラーになる）

2024-08-05 08:00 UTC, naohanpen commented on src/app/committee/news/[news_id]/edit/EditNewsForm.tsx
> +  const [attachments] = useState<FilesFormType>(new Map([["attachments", null]]));
このページはアップロード方式未変更だったので、変更します！

2024-08-05 08:00 UTC, naohanpen commented
オブジェクトストレージのダウンにより保留中...

2024-08-09 03:31 UTC, naohanpen commented
- [ ] ファイルのアップロードに失敗しているのに、完了しましたトーストが表示される（エラーが適切に投げられていない）

2024-08-09 22:32 UTC, naohanpen commented on src/common_components/form_editor/FormEditor.tsx
> +                        disabled={editable === false ? true : undefined}
```disabled?: boolean | undefined;``` なので良いはずなのですが、何かうまくいかないので、、汗

2024-08-09 22:36 UTC, naohanpen commented on src/common_components/form_editor/FormFieldEditor.tsx
> +  const disabled_prop: true | undefined = disabled !== false ? undefined : true;
こちらも別のレビュー同様、何故か動かないので、、汗
そのうち調べます

2024-08-14 05:12 UTC, appare45 approved these changes
感謝

2024-08-14 05:13 UTC, merged